### ISSUE TITLE
Not all messages are broadcasted. 

### ISSUE THREAD

**Issue by jokerigno** [greghesp/assistant-relay#176]
**Describe the bug**
Hi,

as shared on Discord I noticed that some messages are not broacasted. 
Looking in home page or in sandbox I clicked on the play button and noticed that sometimes the response from google is something like "sorry, I can't help you" (in my native language-italian) and sometimes are broadcasted.

**To Reproduce**

Using this template it doesn't work:

{
    "user": "Home-Assistant",
    "command": "La lavatrice è terminata.",
    "broadcast": true
}

Using this it works:

{
    "user": "Home-Assistant",
    "command": "La lavastoviglie è terminata.",
    "broadcast": true
}

(lavatrice means washer, lavastoviglie means dishwasher)

The VERY strange thing is that if I typo the word lavatrice to laatrice it works! So I don't know what to think.

**Expected behavior**

To reproduce broadcast in all situations.

**Desktop (please complete the following information):**
-  Home Assistant Addon inside an Unraid Server
 - Chrome latest version
 - v3.2.0 stable

**Comment by ryancasler** [comment]
Have you tried adding any extra words to see if the broadcast works?  Like, instead of saying "the waster is finished" try saying "The washer is complete" or "The washer is now finished" (And just to check Google Translate, i think those would be "La lavatrice è completa" and "La lavatrice è ora terminata" 😄 )  It might just be something with the Italian translation that is getting screwed up because all of those phrases work fine for me in English.  I would think that none of it would matter in a broadcast.  

At first I thought it might be the accent marks, but it appears that both phrases only have one accent.  But have you tried it without the accented e?  (I don't event know if that's possible in Italien...just giving you some things to try out.)

Have you tried issuing the broadcast from your phone by text?  If you launch the Google Assistant on your phone and then tap the keyboard, you can type in Broadcast followed by the phrase you want to broadcast to your speakers.  That is the definitive way to know if the problem is assistant or assistant relay.  I would have tried that myself but I'd have to reset everything to Italian!  😉

**Comment by greghesp** [comment]
I've reported this one to Google and they're already aware of the issue.  Guess we'll have to play the waiting game

**Comment by jokerigno** [comment]
I was afraid of that.

**Comment by am80l** [comment]
No idea if this is related, but I ran into a similar scenario inside a blueprint where some messages were being broadcast and others weren't. I ended up with this odd syntax after trial and error:

```
      - service: rest_command.assistant_broadcast
        data:
          command: "message: {{ resolved_message }}"
```
In this case, prefixing anything other than `message:` (e.g. "foobar:") fixed the issue, but also caused the "foobar:" string to be broadcast. By using the term "message:" Google ignored that part of the pattern and only broadcast the `{{ resolved_message }}` and also fixed the instances where it wasn't broadcasting anything at all.

I'm not sure what the exact issue is here, but it seems that approach works okay as a work-around, it might be worth a try to see if it resolves this use case also.

**Comment by jokerigno** [comment]
Uhm I would love to test it on my system but I don't know how.

In my setup I use AR as notify service that is called by many automations. So I have this:

```
rest_command:
  assistant_broadcast:
    url: http://192.168.2.101:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Home-Assistant", "broadcast":true}'
  assistant_converse:
    url: http://192.168.2.101:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Home-Assistant", "converse":true}'
  assistant_relay:
    url: http://192.168.2.101:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"Home-Assistant"}'


notify:
  - name: Google Assistant
    platform: rest
    resource: http://192.168.2.101:3000/assistant
    headers:
      Content-Type: application/json
    method: POST_JSON
    message_param_name: command
    data:
      user: Home-Assistant
      broadcast: true
```

Where in your opinion I have to modify? TY!
